### ISSUE TITLE
Wrong encoding detected for UTF-8 file

### ISSUE THREAD

**Issue by wvengen** [jmhodges/rchardet#20]
Using rchardet 1.4.2 with the following file

```
abcdefg abcdefg abcdef
abcdefg abcdefg abcdef ◎abc
```

the wrong encoding is detected
```ruby
require 'rchardet'
CharDet.detect(File.open('a.txt', 'rb').read)
# => {"encoding"=>"ISO-8859-2", "confidence"=>0.5207664687035084}
```

Note the unicode character "◎". Removing some characters returns the correct encoding (but it depends on which characters one removes, I found no logic).

**Comment by grosser** [comment]
rchardet is just guessing, there is no reliable way to get an encoding from just 1 multibyte character -> confidence is low, so maybe just use the encoding when the confidence is high and assume utf-8 otherwise
