### ISSUE TITLE
rchardet19 upgrade

### ISSUE THREAD

**Issue by Laykou** [jmhodges/rchardet#34]
Is there any specific dependency on rchardet19 gem or could it be upgraded to latest rchardet? 

https://github.com/jmhodges/rchardet

If we use e.g. git gem which has this as dependency, there is conflict in some constants with `rchardet19` version.

```
gems/rchardet19-1.3.7/lib/rchardet19.rb:59: warning: already initialized constant CharDet::VERSION
gems/rchardet-1.8.0/lib/rchardet/version.rb:2: warning: previous definition of VERSION was here
```

I know it's only warning, but I'd like to resolve it

**Comment by grosser** [comment]
you should not be using both of them afaik rchardet19 is dead (it was a fork to work with ruby 19 but now rchardet also supports that) last release was 2014 https://rubygems.org/gems/rchardet19

**Comment by Laykou** [comment]
I apologize, I wanted to post this under https://github.com/railslove/cmxl not here.
